-- MCShop player client: login first, then main menu.
-- Requires an Advanced Computer and wireless modem.
local SERVER_ID=2
if fs.exists("shop_settings") then local f=fs.open("shop_settings","r"); SERVER_ID=tonumber(f.readAll()) or SERVER_ID; f.close() end
local PROTOCOL="mcshop"; local modem=peripheral.find("modem")
if not modem or not modem.isWireless() then error("Attach a wireless modem") end
if not term.isColor() then error("This GUI requires an Advanced Computer") end
rednet.open(peripheral.getName(modem)); local logged=false; local username=""; local balance=0; local items={}; local category="All"; local page=1; local categories={"All","Blocks","Resources","Tools","Food","Modded"}
local function request(t) rednet.send(SERVER_ID,t,PROTOCOL); local _,r=rednet.receive(PROTOCOL,10); return r or {success=false,error="Shop server did not respond"} end
local function fit(s,n) s=tostring(s or ""); if #s>n then return s:sub(1,math.max(1,n-1)).."~" end; return s..string.rep(" ",math.max(0,n-#s)) end
local function clear() term.setBackgroundColor(colors.black); term.setTextColor(colors.white); term.clear(); term.setCursorPos(1,1) end
local function box(x,y,w,h,bg,fg,text) if x<1 or y<1 then return end; w=math.min(w,W-x+1); h=math.min(h,H-y+1); term.setBackgroundColor(bg); term.setTextColor(fg or colors.white); for r=0,h-1 do term.setCursorPos(x,y+r); term.write(string.rep(" ",w)) end; if text then term.setCursorPos(x+math.max(0,math.floor((w-#text)/2)),y+math.floor(h/2)); term.write(fit(text,w)) end; term.setBackgroundColor(colors.black) end
local function button(x,y,w,text,bg) box(x,y,w,1,bg,colors.white,text) end
local function pause() term.setCursorPos(1,H); term.setTextColor(colors.lightGray); term.write("Press Enter"); read() end
local function categoryFor(id) local n=id:lower(); if n:find("_sword") or n:find("_pickaxe") or n:find("_axe") or n:find("_shovel") or n:find("_hoe") or n:find("_helmet") or n:find("_chestplate") or n:find("_leggings") or n:find("_boots") then return "Tools" end; if n:find("_block") or n:find("stone") or n:find("_planks") or n:find("_log") or n:find("_ore") or n:find("obsidian") then return "Blocks" end; if n:find("bread") or n:find("apple") or n:find("carrot") or n:find("potato") or n:find("food") then return "Food" end; if not n:find("minecraft:") then return "Modded" end; return "Resources" end
local function visible() local out={}; for _,v in ipairs(items) do if category=="All" or categoryFor(v.id)==category then table.insert(out,v) end end; return out end
local function loadItems() local r=request({action="catalog"}); if r.success then items=r.items; return true end; return false end
local function login()
 clear(); W,H=term.getSize(); box(1,1,W,2,colors.gray,colors.yellow,"MCShop Login"); term.setTextColor(colors.white); term.setCursorPos(2,5); term.write("Minecraft username: "); local n=read(); local r=request({action="request_pin",username=n}); term.setCursorPos(2,7); term.write(fit(r.message or r.error,W-3)); if r.success then term.setCursorPos(2,9); term.write("Check your private whisper."); term.setCursorPos(2,10); term.write("PIN: "); local p=read(); r=request({action="verify_pin",username=n,pin=p}); term.setCursorPos(2,12); term.write(fit(r.error or "Login successful",W-3)); if r.success then logged=true; username=r.username; balance=r.balance end end; if not logged then pause() end
end
local function historyPage()
 clear(); W,H=term.getSize(); button(1,1,9,"< BACK",colors.blue); box(11,1,W-10,2,colors.gray,colors.yellow,"TRANSACTION HISTORY"); local r=request({action="history"}); local y=4; if not r.success then term.setCursorPos(2,y); term.write(fit(r.error,W-3)) elseif #r.transactions==0 then term.setCursorPos(2,y); term.write("No transactions yet") else for i=math.max(1,#r.transactions-12),#r.transactions do local t=r.transactions[i]; term.setCursorPos(2,y); term.write(fit(t.action.." "..t.quantity.."x "..t.item.."  "..t.amount,W-3)); y=y+1; if y>=H-1 then break end end end; while true do local e,b,x,y=os.pullEvent("mouse_click"); if x<=10 and y==1 then return end end
end
local function bankPage()
 while true do
  clear(); W,H=term.getSize(); button(1,1,9,"< BACK",colors.blue); box(11,1,W-10,2,colors.gray,colors.yellow,"BANK"); term.setTextColor(colors.white); term.setCursorPos(2,4); term.write("Account: "..username); term.setCursorPos(2,5); term.write("Balance: "..balance); button(2,8,18,"TRANSFER",colors.blue); button(22,8,18,"LOAN APPLICATION",colors.orange); button(2,10,18,"LOAN STATUS",colors.purple); local e,b,x,y=os.pullEvent("mouse_click")
  if y==1 and x<=10 then return
  elseif y==8 and x>=2 and x<20 then term.setCursorPos(2,13); term.write("Recipient: "); local target=read(); term.setCursorPos(2,14); term.write("Amount: "); local amount=tonumber(read()); local r=request({action="transfer",target=target,amount=amount}); term.setCursorPos(2,16); term.write(fit(r.error or "Transfer complete",W-3)); if r.success then balance=r.balance end; pause()
  elseif y==8 and x>=22 and x<40 then term.setCursorPos(2,13); term.write("Loan amount: "); local amount=tonumber(read()); local q=request({action="loan_quote",amount=amount}); if not q.success then term.setCursorPos(2,15); term.write(fit(q.error,W-3)); pause() else local v=q.quote; term.setCursorPos(2,14); term.write(fit("Fee: "..v.initiationFee.."  Net payout: "..v.netPayout,W-3)); term.setCursorPos(2,15); term.write(fit("Interest: "..v.totalInterest.."  Total repay: "..v.totalRepayment,W-3)); term.setCursorPos(2,16); term.write(fit("Term: "..v.termDays.." days  First installment: "..v.installments[1].installment,W-3)); term.setCursorPos(2,17); term.write("Apply? Type Y or N: "); local yes=read():lower(); if yes=="y" then local r=request({action="loan_request",amount=amount}); term.setCursorPos(2,18); term.write(fit(r.error or "Application submitted",W-3)) end; pause() end
  elseif y==10 and x>=2 and x<20 then local r=request({action="loan_status"}); clear(); term.write("LOAN STATUS"); term.setCursorPos(2,4); if not r.loan then term.write("No loan application") else local l=r.loan; term.write("Status: "..l.status); term.setCursorPos(2,5); term.write("Principal: "..l.principal); term.setCursorPos(2,6); term.write("Remaining: "..(l.remaining or 0)); term.setCursorPos(2,7); term.write("Arrears: "..(l.arrears or 0)); term.setCursorPos(2,8); term.write("Total repay: "..(l.totalRepayment or 0)) end; pause() end
 end
end
local function detail(item)
 clear(); W,H=term.getSize(); button(1,1,9,"< BACK",colors.blue); box(11,1,W-10,2,colors.gray,colors.yellow,fit(item.name,W-10)); term.setTextColor(colors.white); term.setCursorPos(2,4); term.write(fit(item.id,W-3)); term.setCursorPos(2,6); term.write("Buy:  "..item.buy.." credits"); term.setCursorPos(2,7); term.write("Sell: "..item.sell.." credits"); local bw=math.max(8,math.floor((W-6)/3)); button(2,10,bw,"BUY",colors.green); button(3+bw,10,bw,"SELL",colors.orange); button(4+bw*2,10,bw,"BACK",colors.blue); while true do local e,b,x,y=os.pullEvent("mouse_click"); if y==1 and x<=10 then return elseif y==10 and x>=4+bw*2 then return elseif y==10 and x>=2 and x<2+bw or y==10 and x>=3+bw and x<3+2*bw then local action=x<2+bw and "buy" or "sell"; term.setCursorPos(2,13); term.write("Quantity: "); local q=tonumber(read()); local r=request({action=action,item=item.id,quantity=q}); term.setCursorPos(2,15); term.write(fit(r.error or (action.." successful"),W-3)); if r.success then balance=r.balance; term.setCursorPos(2,16); term.write(fit("Amount: "..r.amount.."  Balance: "..balance,W-3)) end; term.setCursorPos(2,H); term.write("Click an action or Back") end end
end
local function shopPage()
 if not loadItems() then clear(); term.write("Could not load catalog"); pause(); return end
 while true do
  clear(); W,H=term.getSize(); button(1,1,9,"< BACK",colors.blue); box(11,1,W-10,2,colors.gray,colors.yellow,"SHOP  "..username.."  $"..balance); local tx=1; for _,c in ipairs(categories) do local cw=#c+2; if tx+cw<=W-10 then button(tx,3,cw,c,c==category and colors.orange or colors.blue); tx=tx+cw+1 end end; local shown=visible(); local cols=math.max(1,math.min(4,math.floor((W-2)/12))); local tileW=math.floor((W-2-(cols-1))/cols); local rows=math.max(1,math.floor((H-8)/4)); local maxPage=math.max(1,math.ceil(#shown/(cols*rows))); page=math.min(page,maxPage); local first=(page-1)*cols*rows+1; for r=0,rows-1 do for c=0,cols-1 do local item=shown[first+r*cols+c]; if item then local bx=1+c*(tileW+1); local by=6+r*4; box(bx,by,tileW,3,colors.lightBlue,colors.black,fit(item.name,tileW)); term.setBackgroundColor(colors.black); term.setTextColor(colors.gray); term.setCursorPos(bx,by+3); term.write(fit("$"..item.buy.." / $"..item.sell,tileW)) end end end; button(2,H-2,8,"PREV",colors.blue); button(12,H-2,8,"NEXT",colors.blue); term.setTextColor(colors.lightGray); term.setCursorPos(2,H); term.write("Hover for name; click an item")
  local e,b,x,y=os.pullEvent(); if e=="mouse_click" then if y==1 and x<=10 then return elseif y==3 then local p=1; for _,c in ipairs(categories) do local cw=#c+2; if p+cw<=W-10 then if x>=p and x<p+cw then category=c; page=1 end; p=p+cw+1 end end elseif y==H-2 and x>=2 and x<10 then page=math.max(1,page-1) elseif y==H-2 and x>=12 and x<20 then page=page+1 elseif y>=6 and y<H-2 then local rr=math.floor((y-6)/4); local cc=math.floor((x-1)/(tileW+1)); if cc>=0 and cc<cols and rr>=0 and rr<rows then local item=shown[first+rr*cols+cc]; if item then detail(item) end end end end
 end
end
local function home()
 while logged do
  clear(); W,H=term.getSize(); box(1,1,W,3,colors.gray,colors.yellow,"MCShop"); term.setTextColor(colors.white); term.setCursorPos(3,2); term.write(username.."   Balance: "..balance); button(2,6,14,"SHOP",colors.green); button(18,6,14,"BANK",colors.blue); button(34,6,14,"HISTORY",colors.purple); button(2,8,14,"LOGOUT",colors.red); term.setCursorPos(2,11); term.setTextColor(colors.lightGray); term.write("Choose a section")
  local e,b,x,y=os.pullEvent("mouse_click"); if y==6 and x>=2 and x<16 then shopPage() elseif y==6 and x>=18 and x<32 then bankPage() elseif y==6 and x>=34 and x<48 then historyPage() elseif y==8 and x>=2 and x<16 then logged=false; username=""; balance=0 end
 end
end
while true do if not logged then login() else home() end end
