-- MCShop admin GUI. Run on a separate Advanced Computer with wireless modem.
local SERVER_ID=2
if fs.exists("shop_settings") then local f=fs.open("shop_settings","r"); SERVER_ID=tonumber(f.readAll()) or SERVER_ID; f.close() end
local P="mcshop"; local modem=peripheral.find("modem")
if not modem or not modem.isWireless() then error("Attach a wireless modem") end
if not term.isColor() then error("Use an Advanced Computer") end
rednet.open(peripheral.getName(modem)); local W,H=term.getSize(); local authed=false; local items={}; local accounts={}; local page=1
local function req(t) rednet.send(SERVER_ID,t,P); local _,r=rednet.receive(P,10); return r or {success=false,error="Server did not respond"} end
local function cls() term.setBackgroundColor(colors.black); term.setTextColor(colors.white); term.clear(); term.setCursorPos(1,1) end
local function fit(s,n) s=tostring(s or ""); return #s>n and s:sub(1,n-1).."~" or s..string.rep(" ",math.max(0,n-#s)) end
local function btn(x,y,w,s,c) if x<1 or y<1 or x>W or y>H then return end; term.setBackgroundColor(c); term.setTextColor(colors.white); term.setCursorPos(x,y); term.write(fit(s,math.min(w,W-x+1))); term.setBackgroundColor(colors.black) end
local function pause() term.setCursorPos(1,H); term.setTextColor(colors.lightGray); term.write("Press Enter"); read() end
local function login() cls(); term.setTextColor(colors.yellow); term.write("MCShop Admin Login"); term.setTextColor(colors.white); term.setCursorPos(2,4); term.write("Admin key: "); local key=read(); local r=req({action="admin_login",key=key}); term.setCursorPos(2,6); term.write(fit(r.error or "Admin login successful",W-2)); if r.success then authed=true end; pause() end
local function refreshAccounts() local r=req({action="admin_accounts"}); if r.success then accounts=r.accounts end end
local function bank() refreshAccounts(); while true do cls(); term.setTextColor(colors.yellow); term.write("BANK - PLAYER ACCOUNTS"); term.setTextColor(colors.white); term.setCursorPos(2,3); term.write("Click a player to manage balance"); local first=(page-1)*math.max(1,H-7)+1; local last=math.min(#accounts,first+H-8); for i=first,last do local y=5+i-first; term.setCursorPos(2,y); term.write(fit(accounts[i].username,W-14).." "); btn(W-10,y,9,"$"..accounts[i].balance,colors.blue) end; btn(2,H-1,8,"PREV",colors.blue); btn(12,H-1,8,"NEXT",colors.blue); btn(W-10,H-1,9,"BACK",colors.red); local e,b,x,y=os.pullEvent("mouse_click"); if y==H-1 and x>=W-10 then return elseif y==H-1 and x>=2 and x<10 then page=math.max(1,page-1) elseif y==H-1 and x>=12 and x<20 then page=page+1 elseif y>=5 and y<=last-first+5 then local a=accounts[first+y-5]; if a then cls(); term.write("Account: "..a.username); term.setCursorPos(2,4); term.write("Current balance: "..a.balance); term.setCursorPos(2,6); term.write("Enter new balance (absolute): "); local amount=tonumber(read()); if amount then local r=req({action="admin_balance",username=a.username,mode="set",amount=amount}); term.setCursorPos(2,8); term.write(r.error or ("Saved balance: "..r.balance)); pause(); refreshAccounts() end end end end
end
local function catalog() local r=req({action="admin_catalog"}); if r.success then items=r.items end; while true do cls(); term.setTextColor(colors.yellow); term.write("CATALOG / PRICES"); term.setTextColor(colors.white); local cols=math.max(1,math.floor((W-2)/26)); local tileW=math.floor((W-2-(cols-1))/cols); local rows=math.max(1,H-5); local perPage=cols*rows; local maxPage=math.max(1,math.ceil(#items/perPage)); page=math.min(page,maxPage); local first=(page-1)*perPage+1; local last=math.min(#items,first+perPage-1); for i=first,last do local z=i-first; local col=z%cols; local row=math.floor(z/cols); local x=2+col*(tileW+1); local y=4+row; term.setBackgroundColor(colors.gray); term.setTextColor(colors.white); term.setCursorPos(x,y); term.write(fit(items[i].name.." B:"..items[i].buy.." S:"..items[i].sell,tileW)); end; btn(2,H-1,8,"PREV",colors.blue); btn(12,H-1,8,"NEXT",colors.blue); btn(W-10,H-1,9,"BACK",colors.red); local e,b,x,y=os.pullEvent("mouse_click"); if y==H-1 and x>=W-10 then return elseif y==H-1 and x>=2 and x<10 then page=math.max(1,page-1) elseif y==H-1 and x>=12 and x<20 then page=page+1 elseif y>=4 and y<4+rows then local col=math.floor((x-2)/(tileW+1)); local row=y-4; local i=first+row*cols+col; local a=items[i]; if col>=0 and col<cols and a then cls(); term.write(a.name); term.setCursorPos(2,4); term.write("Buy price: "); local buy=tonumber(read()); term.setCursorPos(2,6); term.write("Sell price: "); local sell=tonumber(read()); local z=req({action="admin_set_price",item=a.id,buy=buy,sell=sell}); term.setCursorPos(2,8); term.write(z.error or "Saved"); pause(); r=req({action="admin_catalog"}); if r.success then items=r.items end end end end
end
local function loans()
 local r=req({action="admin_loans"}); if not r.success then cls(); term.write(r.error); pause(); return end; while true do cls(); term.setTextColor(colors.yellow); term.write("LOANS / ARREARS"); term.setTextColor(colors.white); local shown=r.loans; local last=math.min(#shown,H-5); for i=1,last do local l=shown[i]; term.setCursorPos(2,3+i); term.write(fit(l.username,W-28).." P:"..fit(l.principal,6).." R:"..fit(l.remaining,6).." A:"..fit(l.arrears,6).." "..l.status) end; btn(2,H-1,9,"REFRESH",colors.green); btn(14,H-1,9,"BACK",colors.red); local e,b,x,y=os.pullEvent("mouse_click"); if y==H-1 and x>=14 then return elseif y==H-1 and x<11 then r=req({action="admin_loans"}) elseif y>=4 and y<=last+3 then local l=shown[y-3]; if l and l.status=="pending" then cls(); term.write("Pending loan: "..l.username); term.setCursorPos(2,4); term.write("Approve or reject? type A or R: "); local d=read():lower(); local z=req({action="admin_loan_decide",username=l.username,decision=d=="a" and "approve" or "reject"}); term.setCursorPos(2,6); term.write(z.error or ("Loan "..(d=="a" and "approved" or "rejected"))); pause(); r=req({action="admin_loans"}) end end end
end
while not authed do login() end
while true do cls(); term.setTextColor(colors.yellow); term.write("MCShop ADMIN"); term.setTextColor(colors.white); btn(2,4,14,"BANK",colors.blue); btn(18,4,14,"CATALOG",colors.green); btn(34,4,14,"IMPORT",colors.orange); btn(2,6,14,"LOANS",colors.purple); btn(18,6,14,"LOGOUT",colors.red); term.setCursorPos(2,9); term.setTextColor(colors.lightGray); term.write("Manage accounts, loans, and prices"); local e,b,x,y=os.pullEvent("mouse_click"); if y==4 and x>=2 and x<16 then page=1; bank() elseif y==4 and x>=18 and x<32 then page=1; catalog() elseif y==4 and x>=34 and x<48 then local r=req({action="admin_import"}); cls(); term.write(r.error or ("Imported "..r.count.." items")); pause() elseif y==6 and x>=2 and x<16 then loans() elseif y==6 and x>=18 and x<32 then req({action="admin_logout"}); authed=false end end
